AWSTemplateFormatVersion: 2010-09-09


# https://s3.amazonaws.com/cloudformation.jsonize.com/cloudfront-s3-viewer-lambda-edge.yaml

# CAUTION: This OVERWRITES the bucket policy of the s3 bucket.


Description: Resources for an S3-CDN with a viewer edge lambda function.


Parameters:

  AcmCertificateArn:
    Type: String
    Description: The ARN of the SSL certificate to use for the CloudFront distribution.

  LambdaFunctionArn:
    Type: String
    Description: The ARN of the Lambda function to use as viewer request.

  ZoneDomain:
    Type: String
    Description: The zone domain for the resource

  SubDomain:
    Type: String
    Description: The sub domain for the system

  S3BucketName:
    Type: String
    Description: The s3 bucket.


Resources:

  TheCloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    DependsOn:
      - TheCloudFrontOriginAccessIdentity
    Properties:
      DistributionConfig:
        Aliases:
          - !Join [ ".", [ !Ref SubDomain, !Ref ZoneDomain ] ]
        CacheBehaviors:
          - PathPattern: /*
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
            Compress: true
            ResponseHeadersPolicyId: 5cc3b908-e619-4b99-88e5-2cf7f45965bd
            ForwardedValues:
              QueryString: false
              Cookies:
                Forward: none
              Headers:
                - Access-Control-Request-Headers
                - Access-Control-Request-Methods
            LambdaFunctionAssociations:
              - EventType: viewer-request
                LambdaFunctionARN: !Ref LambdaFunctionArn
            TargetOriginId: TheS3Bucket
        DefaultCacheBehavior:
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          Compress: true
          ResponseHeadersPolicyId: 5cc3b908-e619-4b99-88e5-2cf7f45965bd
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
            Headers:
              - Access-Control-Request-Headers
              - Access-Control-Request-Methods
          TargetOriginId: TheS3Bucket
        CustomErrorResponses:
          - ErrorCode: 403
            ResponseCode: 403
            ResponsePagePath: /errors/403.html
          - ErrorCode: 404
            ResponseCode: 404
            ResponsePagePath: /errors/404.html
        Enabled: true
        HttpVersion: http2
        Origins:
          - DomainName: !Join [ "", [ !Ref S3BucketName, ".s3.amazonaws.com" ] ]
            Id: TheS3Bucket
            S3OriginConfig:
              OriginAccessIdentity: !Join [ "", [ "origin-access-identity/cloudfront/", !Ref TheCloudFrontOriginAccessIdentity ] ]
        PriceClass: PriceClass_All
        ViewerCertificate:
          AcmCertificateArn: !Ref AcmCertificateArn
          MinimumProtocolVersion: TLSv1.2_2021
          SslSupportMethod: sni-only
      Tags:
        - Key: Domain
          Value: !Join [ ".", [ !Ref SubDomain, !Ref ZoneDomain ] ]

  TheCloudFrontOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Join [ "", [ "CloudFront OAI for ", !Join [ ".", [ !Ref SubDomain, !Ref ZoneDomain ] ] ] ]

  TheRoute53CloudfrontEntry:
    Type: AWS::Route53::RecordSet
    DependsOn:
      - TheCloudFrontDistribution
    Properties:
      HostedZoneName: !Join [ "", [ !Ref ZoneDomain, "." ] ]
      Name: !Join [ ".", [ !Ref SubDomain, !Ref ZoneDomain ] ]
      Type: CNAME
      TTL: '900'
      ResourceRecords:
        - !GetAtt TheCloudFrontDistribution.DomainName

  TheS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    DependsOn:
      - TheCloudFrontOriginAccessIdentity
    Properties:
      Bucket: !Ref S3BucketName
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              CanonicalUser:
                Fn::GetAtt: [ TheCloudFrontOriginAccessIdentity , S3CanonicalUserId ]
            Action: "s3:GetObject"
            Resource: !Sub "arn:aws:s3:::${S3BucketName}/*"


Outputs:

  DomainName:
    Description: The DomainName of CloudFront
    Value: !GetAtt TheCloudFrontDistribution.DomainName