AWSTemplateFormatVersion: 2010-09-09


# https://s3.amazonaws.com/cloudformation.jsonize.com/cloudfront-s3-static-hosting.yaml


Description: Resources for an S3-CDN.


Parameters:

  AcmCertificateArn:
    Type: String
    Description: The ARN of the SSL certificate to use for the CloudFront distribution.

  ZoneDomain:
    Type: String
    Description: The zone domain for the resource

  SubDomain:
    Type: String
    Description: The sub domain for the system

  S3BucketName:
    Type: String
    Description: The s3 bucket name.


Resources:

  TheCloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    DependsOn:
      - TheCloudFrontOriginAccessIdentity
      - TheS3Bucket
    Properties:
      DistributionConfig:
        Aliases:
          - !Join [ ".", [ !Ref SubDomain, !Ref ZoneDomain ] ]
        DefaultCacheBehavior:
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          Compress: true
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
            Headers:
              - Access-Control-Request-Headers
              - Access-Control-Request-Methods
          TargetOriginId: TheS3Bucket
        CustomErrorResponses:
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
        Enabled: true
        HttpVersion: http2
        Origins:
          - DomainName: !GetAtt TheS3Bucket.DomainName
            Id: TheS3Bucket
            S3OriginConfig:
              OriginAccessIdentity: !Join [ "", [ "origin-access-identity/cloudfront/", !Ref TheCloudFrontOriginAccessIdentity ] ]
        PriceClass: PriceClass_All
        ViewerCertificate:
          AcmCertificateArn: !Ref AcmCertificateArn
          MinimumProtocolVersion: TLSv1.2_2021
          SslSupportMethod: sni-only
      Tags:
        - Key: Domain
          Value: !Join [ ".", [ !Ref SubDomain, !Ref ZoneDomain ] ]

  TheCloudFrontOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Join [ "", [ "CloudFront OAI for ", !Join [ ".", [ !Ref SubDomain, !Ref ZoneDomain ] ] ] ]

  TheRoute53CloudfrontEntry:
    Type: AWS::Route53::RecordSet
    DependsOn:
      - TheCloudFrontDistribution
    Properties:
      HostedZoneName: !Join [ "", [ !Ref ZoneDomain, "." ] ]
      Name: !Join [ ".", [ !Ref SubDomain, !Ref ZoneDomain ] ]
      Type: CNAME
      TTL: '900'
      ResourceRecords:
        - !GetAtt TheCloudFrontDistribution.DomainName

  TheS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref S3BucketName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  TheS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    DependsOn:
      - TheS3Bucket
      - TheCloudFrontOriginAccessIdentity
    Properties:
      Bucket: !Ref S3BucketName
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              CanonicalUser:
                Fn::GetAtt: [ TheCloudFrontOriginAccessIdentity , S3CanonicalUserId ]
            Action: "s3:GetObject"
            Resource: !Sub "${TheS3Bucket.Arn}/*"