AWSTemplateFormatVersion: 2010-09-09

# https://s3.amazonaws.com/cloudformation.jsonize.com/cloudwatch-alarms-to-teams.yaml

Description: Resources for setting up a CloudWatch alarms to teams integration


Parameters:

  TopicName:
    Type: String
    Description: The SNS topic name
    Default: TeamsAlarm

  TeamsHookUrl:
    Type: String
    Description: The webhook url for Teams


Resources:

  SNSTopic:
    Type: AWS::SNS::Topic
    DependsOn:
      - LambdaFunction
    Properties:
      DisplayName: !Ref TopicName
      TopicName: !Ref TopicName
      Subscription:
        - Protocol: lambda
          Endpoint: !GetAtt LambdaFunction.Arn

  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: logs
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:*
                Resource:
                  - arn:aws:logs:*:*:*

  LambdaFunction:
    Type: AWS::Lambda::Function
    DependsOn:
      - LambdaRole
    Properties:
      Code:
        ZipFile: |
          {{file-read file:./lambda.py indent:true}}
      Environment:
        Variables:
          HOOK_URL: !Ref TeamsHookUrl
      Handler: index.handler
      Role: !GetAtt LambdaRole.Arn
      Runtime: python3.7
      Timeout: 60

  LambdaSNSPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - LambdaFunction
    Properties:
      FunctionName: !GetAtt LambdaFunction.Arn
      Action: lambda:InvokeFunction
      Principal: sns.amazonaws.com
